[build]
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store"

[[headers]]
  for = "/content/projects/*"
  [headers.values]
    Cache-Control = "no-cache"
